version: '3'

services:
  app:
    image: final-image
    ports:
      - "3000:3000"
    networks:
      - webnet

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:
